Markdown  file added
Utkarsh1504/DSA-Java pull request #50
Opened 2021-10-02 12:46 UTC by preeti-14-7

Fixes #7 

#### Short description of what this resolves:

#### What Changes proposed in this pull request:

 - I have added the detail explanation of ArrayList in java.
- I have added some code snippet also.

#### Checklist

- [X] Added description of change
- [X] Added file name matches [File name guidelines](https://github.com/Utkarsh1504/DSA-Java/blob/main/CONTRIBUTING.md#requesting-a-lesson)
- [X] Added code examples, test must pass
- [X] Added documentation so that the program is self-explanatory and educational.
- [X] PR title follows semantic [commit guidelines](https://github.com/Utkarsh1504/DSA-Java/blob/main/CONTRIBUTING.md#requesting-a-lesson)
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 
This is a documentation of DSA in Java

2021-10-02 16:38 UTC, Utkarsh1504 requested changes
Just Some small tweaks and your PR is ready for merge.
The content looks really great!

2021-10-02 16:39 UTC, Utkarsh1504 commented on lessons/arraylist.md
> + <hr>
```suggestion

```
remove these two lines, lesson heading will be there on the site by default

2021-10-02 16:40 UTC, Utkarsh1504 commented on lessons/arraylist.md
> +## Add Elements :
```suggestion
### Add Elements: 
```
make the heading `h3`

2021-10-02 16:41 UTC, Utkarsh1504 commented on lessons/arraylist.md
> +## Output
```suggestion
### Output:
```

2021-10-02 16:41 UTC, Utkarsh1504 commented on lessons/arraylist.md
> +## Output
```suggestion
### Output:
```

2021-10-02 16:41 UTC, Utkarsh1504 commented on lessons/arraylist.md
> +## Output
```suggestion
### Output:
```

2021-10-02 16:42 UTC, Utkarsh1504 commented on lessons/arraylist.md
> +## Output
```suggestion
### Output:
```

2021-10-02 16:44 UTC, Utkarsh1504 commented on lessons/arraylist.md
> +    playerName.add("Virat");
playerName is not defined??

2021-10-02 16:45 UTC, Utkarsh1504 commented on lessons/arraylist.md
> +    ArrayList<String> animals = new ArrayList<>();
define playerName instead of animals

2021-10-02 16:45 UTC, Utkarsh1504 requested changes
please do these changes

2021-10-03 04:02 UTC, preeti-14-7 commented
Check it again.

2021-10-03 06:26 UTC, Utkarsh1504 approved these changes

2021-10-03 06:27 UTC, Utkarsh1504 commented
Thank you for your work!🎉🎉🎈

2021-10-03 06:27 UTC, merged