Improved the lesson - Added more theory, examples, formatting
Utkarsh1504/DSA-Java pull request #69
Opened 2021-10-03 13:24 UTC by ananya0504

Fixes #63

#### Short description of what this resolves:

improve: Space Complexity #63

#### What Changes proposed in this pull request:
- Added more theory
- Removed the first code snippet and replaced it with a better and easily understandable one
- Added 1 code snippet for finding space complexity in arrays
- Improved overall formatting
- Improved the overall language

#### Checklist

- [x] Added description of change
- [x] Added code examples, the test must pass
- [x] Added documentation so that the program is self-explanatory and educational.
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/Utkarsh1504/DSA-Java/blob/main/CONTRIBUTING.md#requesting-a-lesson)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 
- Improvised on the language of the lesson.
- Removed certain lines which were difficult to understand for beginners
- Added necessary formatting

2021-10-03 18:34 UTC, Utkarsh1504 commented on lessons/space-complexity.md
> +Ex.  If a function A() calls function B() inside it, then all th variables of the function A() will get stored on the system stack temporarily, while the function B() is called and executed inside th
```suggestion
Ex.  If a function A() calls function B() inside it, then all the variables of the function A() will get stored on the system stack temporarily, while the function B() is called and executed inside the function A().
```
please fix this one

2021-10-03 18:35 UTC, Utkarsh1504 requested changes
All looks great, you have improved it in a great way, just fix that typo, and I'll merge your PR.
Thank you!

2021-10-03 19:20 UTC, ananya0504 commented
Okay so I did fixed the typo, and I commit and push it onto my repo

2021-10-03 19:21 UTC, ananya0504 commented on lessons/space-complexity.md
> +Ex.  If a function A() calls function B() inside it, then all th variables of the function A() will get stored on the system stack temporarily, while the function B() is called and executed inside th
Done!

2021-10-04 03:30 UTC, Utkarsh1504 approved these changes
Awesome, Looks good.
Thank you!

2021-10-04 06:29 UTC, merged